### ISSUE TITLE
Why the DataLoader get stuck during training ?

### ISSUE THREAD

**Issue by 7color94** [Microsoft/human-pose-estimation.pytorch#31]
During training, the DataLoader (i.e., torch.utils.data.DataLoader) always got stuck, resulting in the low GPU utilization ? Have you encountered such a situation ?

**Comment by leoxiaobin** [comment]
what do you mean low GPU utilization?

**Comment by ziwei-zh** [comment]
I also have a doubt with GPU utilization...
When transferring the joint coordinate to the gaussian map, we need to do N cycles (N is the number of joints) according to the function "generate_target" in lib/dataset/JointsDataset.py.
So the time complexity is huge and the GPU utilization may be low because most of the time is spent on generating pose ground truth.
Could you explain it? @leoxiaobin
